# Site settings
title:          Android
description:    "android story"
url:            "https://torchlight2016.github.io"

# Author
author:
  name:         torchlight2016
  url:          https://github.com/torchlight2016/android.tale
  email:        developer905@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
